export const TYPE_CONFIGS = [
  {
    render: "antv",
    category: "chart.chart_type_table",
    value: "table-normal",
    title: "chart.chart_table_normal",
    icon: "table-normal",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "tableHeaderBgColor",
        "tableItemBgColor",
        "tableHeaderFontColor",
        "tableFontColor",
        "tableBorderColor",
        "tableScrollBarColor",
        "alpha",
      ],
      "size-selector-ant-v": [
        "tableTitleFontSize",
        "tableItemFontSize",
        "tableHeaderAlign",
        "tableItemAlign",
        "tableTitleHeight",
        "tableItemHeight",
        "tableColumnMode",
        "showIndex",
        "indexLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_table",
    value: "table-info",
    title: "chart.chart_table_info",
    icon: "table-info",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "tableHeaderBgColor",
        "tableItemBgColor",
        "tableHeaderFontColor",
        "tableFontColor",
        "tableBorderColor",
        "tableScrollBarColor",
        "alpha",
      ],
      "size-selector-ant-v": [
        "tablePageMode",
        "tablePageSize",
        "tableTitleFontSize",
        "tableItemFontSize",
        "tableHeaderAlign",
        "tableItemAlign",
        "tableTitleHeight",
        "tableItemHeight",
        "tableColumnMode",
        "showIndex",
        "indexLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_table",
    value: "table-pivot",
    title: "chart.chart_table_pivot",
    icon: "table-pivot",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "total-cfg",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "tableHeaderBgColor",
        "tableItemBgColor",
        "tableHeaderFontColor",
        "tableFontColor",
        "tableBorderColor",
        "tableScrollBarColor",
        "alpha",
      ],
      "size-selector-ant-v": [
        "tableTitleFontSize",
        "tableItemFontSize",
        "tableHeaderAlign",
        "tableItemAlign",
        "tableTitleHeight",
        "tableItemHeight",
        "tableColumnMode",
      ],
      "total-cfg": ["row", "col"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_table",
    value: "table-traceability",
    title: "chart.chart_table_traceability",
    icon: "table-traceability",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import(
            "@/pages/smart-page/propertyeditor/traceability/TraceabilityPropsPanel "
          ),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "tableHeaderBgColor",
        "tableItemBgColor",
        "tableHeaderFontColor",
        "tableFontColor",
        "tableBorderColor",
        "tableScrollBarColor",
        "alpha",
      ],
      "size-selector-ant-v": [
        "tableTitleFontSize",
        "tableItemFontSize",
        "tableHeaderAlign",
        "tableItemAlign",
        "tableTitleHeight",
        "tableItemHeight",
        "tableColumnMode",
        "showIndex",
        "indexLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_quota",
    value: "text-card",
    title: "chart.chart_label",
    icon: "basic-label",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["quotaColor", "dimensionColor"],
      "size-selector-ant-v": [
        "quotaFontSize",
        "quotaFontFamily",
        "quotaFontStyle",
        "quotaLetterSpace",
        "quotaFontShadow",
        "dimensionShow",
        "dimensionFontSize",
        "dimensionFontFamily",
        "dimensionFontStyle",
        "dimensionLetterSpace",
        "dimensionFontShadow",
        "spaceSplit",
        "hPosition",
        "vPosition",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_quota",
    value: "indicator-card",
    title: "chart.chart_card",
    icon: "basic-text",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["quotaColor", "dimensionColor"],
      "size-selector-ant-v": [
        "quotaFontSize",
        "quotaFontFamily",
        "quotaFontStyle",
        "quotaLetterSpace",
        "quotaFontShadow",
        "dimensionShow",
        "dimensionFontSize",
        "dimensionFontFamily",
        "dimensionFontStyle",
        "dimensionLetterSpace",
        "dimensionFontShadow",
        "spaceSplit",
        "hPosition",
        "vPosition",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_quota",
    value: "gauge",
    title: "chart.chart_gauge",
    icon: "gauge",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "custom", "gradient", "alpha"],
      "size-selector-ant-v": [
        "gaugeMin",
        "gaugeMax",
        "gaugeStartAngle",
        "gaugeEndAngle",
        "gaugeTickCount",
      ],
      "label-selector-ant-v": ["labelGauge"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_quota",
    value: "liquid",
    title: "chart.chart_liquid",
    icon: "liquid",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "custom", "alpha"],
      "size-selector-ant-v": ["liquidShape", "liquidMax", "liquidSize"],
      "label-selector-ant-v": ["labelGauge"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },

  {
    render: "antv",
    category: "chart.chart_type_trend",
    value: "line",
    title: "chart.chart_line",
    icon: "basic-line",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": [
        "lineWidth",
        "lineSymbol",
        "lineSymbolSize",
        "lineSmooth",
      ],
      "label-selector-ant-v": ["show", "fontSize", "color"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_trend",
    value: "area",
    title: "chart.chart_area",
    icon: "basic-area",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "alpha",
        "gradient",
      ],
      "size-selector-ant-v": [
        "lineWidth",
        "lineSymbol",
        "lineSymbolSize",
        "lineSmooth",
      ],
      "label-selector-ant-v": ["show", "fontSize", "color"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_trend",
    value: "line-stack",
    title: "chart.chart_line_stack",
    icon: "line-stack",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": [
        "lineWidth",
        "lineSymbol",
        "lineSymbolSize",
        "lineSmooth",
      ],
      "label-selector-ant-v": ["show", "fontSize", "color"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bar",
    title: "chart.chart_bar",
    icon: "bar",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": ["barDefault", "barGap"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-v"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bar-group",
    title: "chart.chart_bar_group",
    icon: "bar-group",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": ["barDefault", "barGap"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-v"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bar-stack",
    title: "chart.chart_bar_stack",
    icon: "bar-stack",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": ["barDefault", "barGap"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-v"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bar-group-stack",
    title: "chart.chart_bar_group_stack",
    icon: "bar-group-stack",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": ["barDefault", "barGap"],
      "label-selector-ant-v": [
        "show",
        "fontSize",
        "color",
        "position-v",
        "labelContent",
      ],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "waterfall",
    title: "chart.chart_waterfall",
    icon: "waterfall",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "custom", "gradient", "alpha"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-v"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bar-horizontal",
    title: "chart.chart_bar_horizontal",
    icon: "bar-horizontal",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": ["barDefault", "barGap"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-h"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bar-stack-horizontal",
    title: "chart.chart_bar_stack_horizontal",
    icon: "bar-stack-horizontal",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "size-selector-ant-v": ["barDefault", "barGap"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-h"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "percentage-bar-stack-horizontal",
    title: "chart.chart_percentage_bar_stack_horizontal",
    icon: "percentage-bar-stack-horizontal",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "label-selector-ant-v": [
        "show",
        "fontSize",
        "color",
        "position-h",
        "reserveDecimalCount",
      ],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "pie",
    title: "chart.chart_pie",
    icon: "pie",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": ["pieOuterRadius"],
      "label-selector-ant-v": [
        "show",
        "fontSize",
        "color",
        "position-pie",
        "labelContent",
        "reserveDecimalCount",
      ],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "pie-donut",
    title: "chart.chart_pie_donut",
    icon: "pie-donut",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": ["pieInnerRadius", "pieOuterRadius"],
      "label-selector-ant-v": [
        "show",
        "fontSize",
        "color",
        "position-pie",
        "labelContent",
        "reserveDecimalCount",
      ],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "pie-rose",
    title: "chart.chart_pie_rose",
    icon: "pie-rose",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": ["pieOuterRadius"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-pie"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "pie-donut-rose",
    title: "chart.chart_pie_donut_rose",
    icon: "pie-donut-rose",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": ["pieInnerRadius", "pieOuterRadius"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-pie"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "percentage-bar-stack",
    title: "chart.chart_percentage_bar_stack",
    icon: "percentage-bar-stack",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "label-selector-ant-v": [
        "show",
        "fontSize",
        "color",
        "position-v",
        "reserveDecimalCount",
      ],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_compare",
    value: "bidirectional-bar",
    title: "chart.chart_bidirectional_bar",
    icon: "bidirectional-bar",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": [
        "value",
        "colorPanel",
        "customColor",
        "gradient",
        "alpha",
      ],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-h"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },

  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "radar",
    title: "chart.chart_radar",
    icon: "radar",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "split-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": ["radarShape", "radarSize"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-v"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
      "split-selector-ant-v": ["splitForm", "name", "lineStyle"],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "treemap",
    title: "chart.chart_treemap",
    icon: "treemap",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "custom", "alpha"],
      "label-selector-ant-v": ["show", "fontSize", "color"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_distribute",
    value: "word-cloud",
    title: "chart.chart_word_cloud",
    icon: "word-cloud",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "custom", "alpha"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },

  {
    render: "antv",
    category: "chart.chart_type_relation",
    value: "scatter",
    title: "chart.chart_scatter",
    icon: "scatter",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "size-selector-ant-v",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "x-axis-selector-ant-v",
      "y-axis-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "size-selector-ant-v": ["scatterSymbol", "scatterSymbolSize"],
      "label-selector-ant-v": ["show", "fontSize", "color"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "x-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "y-axis-selector-ant-v": [
        "show",
        "position",
        "name",
        "nameTextStyle",
        "axisValue",
        "splitLine",
        "axisForm",
        "axisLabel",
      ],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_relation",
    value: "funnel",
    title: "chart.chart_funnel",
    icon: "funnel",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/DataPropsPanel"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: [
      "color-selector",
      "label-selector-ant-v",
      "tooltip-selector-ant-v",
      "title-selector-ant-v",
      "legend-selector-ant-v",
    ],
    propertyInner: {
      "color-selector": ["value", "colorPanel", "customColor", "alpha"],
      "label-selector-ant-v": ["show", "fontSize", "color", "position-h"],
      "tooltip-selector-ant-v": ["show", "textStyle"],
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
      "legend-selector-ant-v": [
        "show",
        "icon",
        "orient",
        "textStyle",
        "hPosition",
        "vPosition",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_others",
    value: "single-line-text",
    title: "chart.single_line_text",
    icon: "single-line-text",
    propertyEditor: [
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: ["title-selector-ant-v"],
    propertyInner: {
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_others",
    value: "richTextView",
    title: "chart.rich_text_view",
    icon: "richTextView",
    propertyEditor: [
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: ["title-selector-ant-v"],
    propertyInner: {
      "title-selector-ant-v": ["title"],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_others",
    value: "tabs-panel",
    title: "chart.tabs_panel",
    icon: "tab-panel",
    propertyEditor: [
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: ["title-selector-ant-v"],
    propertyInner: {
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_others",
    value: "web-page",
    title: "chart.web_page",
    icon: "web-page",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/others/WebPageEditor"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: ["title-selector-ant-v"],
    propertyInner: {
      "title-selector-ant-v": [
        "show",
        "title",
        "fontSize",
        "color",
        "hPosition",
        "isItalic",
        "isBolder",
        "remarkShow",
        "fontFamily",
        "letterSpace",
        "fontShadow",
      ],
    },
  },
  {
    render: "antv",
    category: "chart.chart_type_others",
    value: "page-query",
    title: "chart.page_query",
    icon: "query",
    propertyEditor: [
      {
        name: "DATA",
        component: () =>
          import("@/pages/smart-page/propertyeditor/others/PageQueryEditor"),
      },
      {
        name: "STYLE",
        component: () =>
          import("@/pages/smart-page/propertyeditor/chart/StylePropsPanel"),
      },
    ],
    properties: ["form-selector-ant-v"],
    propertyInner: {
      "form-selector-ant-v": [
        "layout",
        "columnCount",
        "labelCol",
        "wrapperCol",
      ],
    },
  },
];
